# .pre-commit-config.yaml
repos:
  - repo: https://github.com/adrienverge/yamllint
    rev: v1.31.0
    hooks:
      - id: yamllint
        args: [--strict, -c=.yamllint.yaml]
  - repo: https://github.com/DavidAnson/markdownlint-cli2
    rev: v0.17.2
    hooks:
      - id: markdownlint-cli2-rules-docker
  - repo: local
    hooks:
      - id: clippy
        name: clippy
        entry: cargo +nightly clippy
        args: [--all, --, --deny, warnings]
        language: system
        types: [rust]
        pass_filenames: false

      - id: fmt
        name: rustfmt
        entry: cargo +nightly fmt
        args: [--all, --, --check]
        language: system
        types: [rust]
        pass_filenames: false
