---
apiVersion: bpfman.io/v1alpha1
kind: ClusterBpfApplication
metadata:
  labels:
    app.kubernetes.io/name: bpfapplication
  name: app-counter
spec:
  # Select all nodes
  nodeSelector: {}
  byteCode:
    image:
      url: quay.io/bpfman-bytecode/go-app-counter:latest
      imagePullPolicy: Always
  programs:
    - name: kprobe_counter
      type: kprobe
      kprobeInfo:
        links:
          - function: try_to_wake_up
            offset: 0
    - name: tracepoint_kill_recorder
      type: tracepoint
      tracepointInfo:
        links:
          - name: syscalls/sys_enter_kill
    - name: stats
      type: tc
      tcInfo:
        links:
          - interfaceSelector:
              primaryNodeInterface: true
            priority: 55
            direction: ingress
    - name: tcx_stats
      type: tcx
      tcxInfo:
        links:
          - interfaceSelector:
              primaryNodeInterface: true
            priority: 500
            direction: ingress
    - name: uprobe_counter
      type: uprobe
      uprobeInfo:
        links:
          - function: main.getCount
            target: /go-target
            containers:
              namespace: go-target
              pods: {}
              containerNames:
                - go-target
    - name: xdp_stats
      type: xdp
      xdpInfo:
        links:
          - interfaceSelector:
              primaryNodeInterface: true
            priority: 55
